name: mlfold
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - appnope=0.1.3
  - asttokens=2.4.1
  - backports=1.0
  - backports.functools_lru_cache=1.6.5
  - blas=1.0=mkl
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - ca-certificates=2023.7.22
  - certifi=2023.7.22
  - cffi=1.15.1
  - charset-normalizer=2.0.4
  - comm=0.1.4
  - cryptography=41.0.3
  - debugpy=1.6.7
  - decorator=5.1.1
  - exceptiongroup=1.1.3
  - executing=2.0.1
  - ffmpeg=4.3
  - freetype=2.12.1
  - gettext=0.21.0
  - giflib=5.2.1
  - gmp=6.2.1
  - gnutls=3.6.15
  - icu=73.1
  - idna=3.4
  - importlib-metadata=6.8.0
  - importlib_metadata=6.8.0
  - intel-openmp=2023.1.0
  - ipykernel=6.26.0
  - ipython=8.17.2
  - jedi=0.19.1
  - jpeg=9e
  - jupyter_client=8.6.0
  - jupyter_core=5.5.0
  - lame=3.100
  - lcms2=2.12
  - lerc=3.0
  - libcxx=14.0.6
  - libdeflate=1.17
  - libffi=3.4.4
  - libiconv=1.16
  - libidn2=2.3.4
  - libpng=1.6.39
  - libsodium=1.0.18
  - libtasn1=4.19.0
  - libtiff=4.5.1
  - libunistring=0.9.10
  - libwebp=1.3.2
  - libwebp-base=1.3.2
  - libxml2=2.10.4
  - llvm-openmp=14.0.6
  - lz4-c=1.9.4
  - matplotlib-inline=0.1.6
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.8
  - mkl_random=1.2.4
  - ncurses=6.4
  - nest-asyncio=1.5.8
  - nettle=3.7.3
  - numpy=1.26.0
  - numpy-base=1.26.0
  - openh264=2.1.1
  - openjpeg=2.4.0
  - openssl=3.1.4
  - packaging=23.2
  - parso=0.8.3
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=10.0.1
  - pip=23.3
  - platformdirs=4.0.0
  - prompt-toolkit=3.0.41
  - psutil=5.9.5
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pycparser=2.21
  - pygments=2.16.1
  - pyopenssl=23.2.0
  - pysocks=1.7.1
  - python=3.10.13
  - python-dateutil=2.8.2
  - python_abi=3.10
  - pytorch=1.13.1
  - pyzmq=24.0.1
  - readline=8.2
  - requests=2.31.0
  - setuptools=68.0.0
  - six=1.16.0
  - sqlite=3.41.2
  - stack_data=0.6.2
  - tbb=2021.8.0
  - tk=8.6.12
  - torchaudio=0.13.1
  - torchvision=0.14.1
  - tornado=6.3.3
  - traitlets=5.13.0
  - typing_extensions=4.7.1
  - urllib3=1.26.18
  - wcwidth=0.2.10
  - wheel=0.41.2
  - xz=5.4.2
  - zeromq=4.3.4
  - zipp=3.17.0
  - zlib=1.2.13
  - zstd=1.5.5
  - pip:
      - astunparse==1.6.3
      - biopython==1.81
      - contourpy==1.2.0
      - cycler==0.12.1
      - einops==0.7.0
      - ema-pytorch==0.2.3
      - fonttools==4.44.3
      - jinja2==3.1.2
      - joblib==1.3.2
      - kiwisolver==1.4.5
      - markupsafe==2.1.3
      - matplotlib==3.8.1
      - mdtraj==1.9.9
      - networkx==3.2.1
      - pandas==2.1.3
      - pot==0.9.1
      - pyparsing==3.1.1
      - pytz==2023.3.post1
      - rdkit==2023.3.1
      - scikit-learn==1.3.2
      - scipy==1.11.3
      - seaborn==0.12.2
      - threadpoolctl==3.2.0
      - torch-cluster==1.6.1
      - torch-geometric==2.2.0
      - torch-scatter==2.1.1
      - torch-sparse==0.6.17
      - torch-spline-conv==1.2.2
      - tqdm==4.66.1
      - tzdata==2023.3
# prefix: /Users/mac/anaconda3/envs/mlfold
